services:
  # Grafana Service
  - type: web
    name: grafana-monitoring
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    dockerfilePath: ./grafana-stack/Dockerfile.grafana
    dockerContext: ./grafana-stack
    envVars:
      - key: GF_SECURITY_ADMIN_USER
        value: admin
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: admin
      - key: GF_USERS_ALLOW_SIGN_UP
        value: false
      - key: GF_SERVER_ROOT_URL
        value: https://awtospx.com
      - key: GF_SERVER_SERVE_FROM_SUB_PATH
        value: false
      - key: GF_SECURITY_COOKIE_SECURE
        value: true
      - key: GF_SECURITY_COOKIE_SAMESITE
        value: none
      - key: GF_SECURITY_COOKIE_DOMAIN
        value: awtospx.com
      - key: GF_SECURITY_SESSION_LIFETIME
        value: 86400
      - key: GF_SECURITY_SESSION_REMEMBER_ME_DURATION
        value: 604800
      - key: GF_SECURITY_LOGIN_REMEMBER_DAYS
        value: 30
      - key: GF_SECURITY_DISABLE_GRAVATAR
        value: true
      - key: GF_SECURITY_STRICT_TRANSPORT_SECURITY
        value: true
      - key: GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS
        value: 31536000
    autoDeploy: true

  # AI Service (Simplified)
  - type: web
    name: ai-service
    env: python
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: pip install flask flask-cors requests
    startCommand: python simple_openai_app.py
    rootDir: grafana-stack/ai-service
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # You'll need to set this in Render dashboard
      - key: GRAFANA_URL
        value: https://awtospx.com
      - key: GRAFANA_USER
        value: admin
      - key: GRAFANA_PASSWORD
        value: admin
      - key: PROMETHEUS_URL
        value: https://prometheus.onrender.com
    autoDeploy: true

  # Prometheus Service
  - type: web
    name: prometheus
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /-/healthy
    dockerfilePath: ./grafana-stack/Dockerfile.prometheus
    dockerContext: ./grafana-stack
    autoDeploy: true
